<a href="https://colab.research.google.com/github/NavyaSupriyan/ML-projects-2023/blob/main/NavyaSupriyan_SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.figure_factory as ff
import plotly.express as px
from sklearn import metrics
from sklearn.metrics import confusion_matrix, precision_recall_curve, auc, roc_curve, accuracy_score, recall_score, classification_report, f1_score, average_precision_score, precision_recall_fscore_support, roc_auc_score
import warnings
warnings.filterwarnings('ignore')

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
df=pd.read_csv('/content/drive/MyDrive/IRIS.csv')


In [ ]:
train_data,test_data=train_test_split(df,random_state=0)

In [ ]:
train_data

sepal_length  sepal_width  petal_length  petal_width          species
61            5.9          3.0           4.2          1.5  Iris-versicolor
92            5.8          2.6           4.0          1.2  Iris-versicolor
112           6.8          3.0           5.5          2.1   Iris-virginica
2             4.7          3.2           1.3          0.2      Iris-setosa
141           6.9          3.1           5.1          2.3   Iris-virginica
..            ...          ...           ...          ...              ...
9             4.9          3.1           1.5          0.1      Iris-setosa
103           6.3          2.9           5.6          1.8   Iris-virginica
67            5.8          2.7           4.1          1.0  Iris-versicolor
117           7.7          3.8           6.7          2.2   Iris-virginica
47            4.6          3.2           1.4          0.2      Iris-setosa

[112 rows x 5 columns]

In [ ]:
test_data.shape

(38, 5)

In [ ]:
train_data.shape

(112, 5)

In [ ]:
train_data.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [ ]:
train_data.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [ ]:
train_data.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.054811      0.886818     0.838797
sepal_width      -0.054811     1.000000     -0.356472    -0.300291
petal_length      0.886818    -0.356472      1.000000     0.967351
petal_width       0.838797    -0.300291      0.967351     1.000000

In [ ]:
x=train_data.drop(['species'],axis=1)
y=train_data.species

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=0)

In [ ]:
x_test

sepal_length  sepal_width  petal_length  petal_width
64            5.6          2.9           3.6          1.3
128           6.4          2.8           5.6          2.1
119           6.0          2.2           5.0          1.5
105           7.6          3.0           6.6          2.1
25            5.0          3.0           1.6          0.2
60            5.0          2.0           3.5          1.0
79            5.7          2.6           3.5          1.0
112           6.8          3.0           5.5          2.1
82            5.8          2.7           3.9          1.2
95            5.7          3.0           4.2          1.2
85            6.0          3.4           4.5          1.6
131           7.9          3.8           6.4          2.0
31            5.4          3.4           1.5          0.4
39            5.1          3.4           1.5          0.2
14            5.8          4.0           1.2          0.2
115           6.4          3.2           5.3          2.3
123           6.3          2.7           4.9          1.8
135           7.7          3.0           6.1          2.3
21            5.1          3.7           1.5          0.4
102           7.1          3.0           5.9          2.1
101           5.8          2.7           5.1          1.9
145           6.7          3.0           5.2          2.3
99            5.7          2.8           4.1          1.3
116           6.5          3.0           5.5          1.8
5             5.4          3.9           1.7          0.4
48            5.3          3.7           1.5          0.2
4             5.0          3.6           1.4          0.2
2             4.7          3.2           1.3          0.2

In [ ]:
y_test

64     Iris-versicolor
128     Iris-virginica
119     Iris-virginica
105     Iris-virginica
25         Iris-setosa
60     Iris-versicolor
79     Iris-versicolor
112     Iris-virginica
82     Iris-versicolor
95     Iris-versicolor
85     Iris-versicolor
131     Iris-virginica
31         Iris-setosa
39         Iris-setosa
14         Iris-setosa
115     Iris-virginica
123     Iris-virginica
135     Iris-virginica
21         Iris-setosa
102     Iris-virginica
101     Iris-virginica
145     Iris-virginica
99     Iris-versicolor
116     Iris-virginica
5          Iris-setosa
48         Iris-setosa
4          Iris-setosa
2          Iris-setosa
Name: species, dtype: object

In [ ]:
models={
 "Support Vector Machine":SVC(), "K Nearest Neighbor":KNeighborsClassifier(weights='distance',metric='euclidean',n_neighbors=1), "Logistic Regression": 
 LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True, intercept_scaling=1, l1_ratio=None, max_iter=100, multi_class='auto', 
                          n_jobs=None, penalty='l2',random_state=0, solver='lbfgs', tol=0.0001, verbose=0, warm_start=False)
}

In [ ]:
for name, model in models.items():
  model.fit(x_train,y_train)
  print(name + ' trained.')


Support Vector Machine trained.
K Nearest Neighbor trained.
Logistic Regression trained.


In [ ]:
original_results = []
data = []
columns = ["Accuracy", "Precision", "Recall", "F1-Score"]

for name, model in models.items():
  result = model.score(x_test, y_test)
  original_results.append(result)

  print("""
  __________________________"""+name+"""__________________________
  """)

  model = models[name]
  y_test_pred = model.predict(x_test)
  arg_test = {'y_true':y_test, 'y_pred':y_test_pred}
  
  accuracy = model.score(x_test, y_test)
  precision = metrics.precision_score(y_test, y_test_pred, average='macro')
  recall = metrics.recall_score(y_test, y_test_pred, average='macro')
  f1_score = metrics.f1_score(y_test_pred, y_test, average='macro')

  values = [accuracy, precision, recall, f1_score]
  zipped = zip(columns, values)
  a_dictionary = dict(zipped)
  ##print(a_dictionary)
  data.append(a_dictionary)

  print(confusion_matrix(**arg_test))
  print(classification_report(**arg_test))

  print(name + ': {:.5f}%'.format(result * 100))


  __________________________Support Vector Machine__________________________
  
[[ 9  0  0]
 [ 0  7  0]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.96        28
      macro avg       0.96      0.97      0.96        28
   weighted avg       0.97      0.96      0.96        28

Support Vector Machine: 96.42857%

  __________________________K Nearest Neighbor__________________________
  
[[ 9  0  0]
 [ 0  7  0]
 [ 0  1 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         9
Iris-versicolor       0.88      1.00      0.93         7
 Iris-virginica       1.00      0.92      0.96        12

       accuracy                           0.96        28
      macro avg       0.96      0.97      0.9

In [ ]:
model.score(x_test,y_test)

0.9642857142857143

In [ ]:
model.predict(x_test)

array(['Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [ ]:
train_data.head()

sepal_length  sepal_width  petal_length  petal_width          species
61            5.9          3.0           4.2          1.5  Iris-versicolor
92            5.8          2.6           4.0          1.2  Iris-versicolor
112           6.8          3.0           5.5          2.1   Iris-virginica
2             4.7          3.2           1.3          0.2      Iris-setosa
141           6.9          3.1           5.1          2.3   Iris-virginica